### ISSUE TITLE
Show SSL certificate generation output step failed

### ISSUE THREAD

**Issue by micisse** [nickjj/ansible-letsencrypt#8]
Hello, I got this problem during the ansible process in the "Show SSL certificate generation output" step in main.yml. The problem comes from the file "acme_tiny". I captured the error. Do you have any solution please ?!

![Show SSL Certificate generation output](https://user-images.githubusercontent.com/56940294/86425955-c7def880-bce6-11ea-82dd-a448a162f16f.png)

**Comment by nickjj** [comment]
Hi,

What OS / version are you using? What version of Python are you using? What version of this role are you using?

**Comment by micisse** [comment]
Hi, 

I use Python3 (ansible_python_interpreter="env python3")
I use v0.3.2 realease of this role (the last i think)
OS is Ubuntu 16.04

**Comment by nickjj** [comment]
Which version of Python 3 are you using?

**Comment by micisse** [comment]
$ python3 --version

I've this: **Python 3.5.2**

**Comment by nickjj** [comment]
Have you checked this https://github.com/diafygi/acme-tiny/issues/247?

**Comment by micisse** [comment]
No, thanks for that so with this role, we cannot create wildcard (ex: *.exemple.com). You've any alternative ?! 

`letsencrypt_domains: ["exemple.com", "*.exemple.com"]`

**Comment by nickjj** [comment]
It's a limitation of acme-tiny. It doesn't support doing DNS based validation and DNS validation is required for wildcards.

You'll want to use something else. Maybe https://github.com/acmesh-official/acme.sh or https://github.com/certbot/certbot.

**Comment by micisse** [comment]
Okay thank @nickjj !
